--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: template_cards; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.template_cards (
    id integer NOT NULL,
    uuid character varying(80) NOT NULL,
    card_name character varying(80) NOT NULL,
    upload_date timestamp without time zone NOT NULL,
    "order" integer NOT NULL,
    column_name character varying(80) NOT NULL,
    details jsonb NOT NULL,
    board_id character varying(80) NOT NULL
);


ALTER TABLE public.template_cards OWNER TO admin;

--
-- Name: template_cards_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.template_cards_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.template_cards_id_seq OWNER TO admin;

--
-- Name: template_cards_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--

ALTER SEQUENCE public.template_cards_id_seq OWNED BY public.template_cards.id;


--
-- Name: template_cards id; Type: DEFAULT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.template_cards ALTER COLUMN id SET DEFAULT nextval('public.template_cards_id_seq'::regclass);


--
-- Data for Name: template_cards; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.template_cards (id, uuid, card_name, upload_date, "order", column_name, details, board_id) FROM stdin;
818	0b8f785e-e855-47e1-ba7c-d7139dde5efb	JavaScript Basics	2024-07-09 16:52:12.737	1	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"Article: W3Schools – JavaScript Tutorial https://www.w3schools.com/js/\\"},{\\"checked\\":false,\\"value\\":\\"Article: The Modern JavaScript Tutorial https://javascript.info/\\"},{\\"checked\\":false,\\"value\\":\\"Video: JavaScript Crash Course for Beginners https://youtu.be/hdI2bqOjy3c?t=2\\"},{\\"checked\\":false,\\"value\\":\\"Video: Build a Netflix Landing Page Clone with HTML, CSS & JS https://youtu.be/P7t13SGytRk?t=22\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":60}"	d946ac90-ccd0-4911-b370-5d0d97ddca0c
819	393f3871-ecad-466a-8880-080b801df820	DOM Manipulation	2024-07-09 16:52:12.737	2	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"Article: DOM Tree https://javascript.info/dom-nodes\\"},{\\"checked\\":false,\\"value\\":\\"Article: GeeksForGeeks - DOM (Document Object Model) https://www.geeksforgeeks.org/dom-document-object-model/\\"},{\\"checked\\":false,\\"value\\":\\"Article: What is the DOM? https://www.freecodecamp.org/news/what-is-the-dom-document-object-model-meaning-in-javascript/\\"},{\\"checked\\":false,\\"value\\":\\"Article: Eloquent JavaScript, 3rd Edition: The Document Object Model https://eloquentjavascript.net/14_dom.html\\"},{\\"checked\\":false,\\"value\\":\\"Article: JavaScript HTML DOM https://www.w3schools.com/js/js_htmldom.asp\\"},{\\"checked\\":false,\\"value\\":\\"Article: JavaScript DOM https://www.javascripttutorial.net/javascript-dom/\\"},{\\"checked\\":false,\\"value\\":\\"Article: Learn the HTML DOM with Exercises - CodeGuage https://www.codeguage.com/courses/js/html-dom-introduction\\"},{\\"checked\\":false,\\"value\\":\\"Video: What is DOM, Shadow DOM and Virtual DOM? https://www.youtube.com/watch?v=7Tok22qxPzQ\\"},{\\"checked\\":false,\\"value\\":\\"Video: JavaScript DOM Crash Course https://www.youtube.com/watch?v=0ik6X4DJKCc\\"},{\\"checked\\":false,\\"value\\":\\"Feed: Explore top posts about DOM https://app.daily.dev/tags/dom?ref=roadmapsh\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":150}"	d946ac90-ccd0-4911-b370-5d0d97ddca0c
820	832b2167-f9a7-4164-9b23-0003f3d67f87	HTML Basics	2024-07-09 16:52:12.737	1	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"Article: W3Schools: Learn HTML https://www.w3schools.com/html/html_intro.asp\\"},{\\"checked\\":false,\\"value\\":\\"Article: MDN Docs: Getting Started with HTML https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started\\"},{\\"checked\\":false,\\"value\\":\\"Article: web.dev: Learn HTML https://web.dev/learn/html\\"},{\\"checked\\":false,\\"value\\":\\"Article: HTML Cheatsheet https://htmlcheatsheet.com\\"},{\\"checked\\":false,\\"value\\":\\"Video: HTML Full Course - Build a Website Tutorial https://www.youtube.com/watch?v=pQN-pnXPaVg\\"},{\\"checked\\":false,\\"value\\":\\"Video: HTML Tutorial for Beginners: HTML Crash Course https://www.youtube.com/watch?v=qz0aGYrrlhU\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":90}"	9f1eed82-3acf-4e07-a1bd-1f0b26cf1dca
821	2f8623c7-cb7d-4103-9da2-63666391c62c	Fetch API	2024-07-09 16:52:12.737	3	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"Article: Fetch API MDN Docs https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API\\"},{\\"checked\\":false,\\"value\\":\\"Article: A Simple Guide to JavaScript Fetch API https://www.javascripttutorial.net/javascript-fetch-api/\\"},{\\"checked\\":false,\\"value\\":\\"Article: Introduction to Fetch https://web.dev/introduction-to-fetch/\\"},{\\"checked\\":false,\\"value\\":\\"Video: JavaScript Fetch API https://www.youtube.com/watch?v=-ZI0ea5O2oA\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":80}"	d946ac90-ccd0-4911-b370-5d0d97ddca0c
822	de498281-8b30-4f97-821c-14db3f1af518	Forms and Validations	2024-07-09 16:52:12.737	3	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"Article: MDN Web Docs: Client-side form validation https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation\\"},{\\"checked\\":false,\\"value\\":\\"Article: Learn Forms by web.dev https://web.dev/learn/forms/\\"},{\\"checked\\":false,\\"value\\":\\"Article: W3Schools: JavaScript Form Validation https://www.w3schools.com/js/js_validation.asp\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":45}"	9f1eed82-3acf-4e07-a1bd-1f0b26cf1dca
823	6ecef8d0-9f1b-4ebe-ad64-1883a126c859	Semantic HTML	2024-07-09 16:52:12.737	2	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"Article: Guide to Writing Semantic HTML https://cs.fyi/guide/writing-semantic-html\\"},{\\"checked\\":false,\\"value\\":\\"Article: W3Schools: Semantic HTML https://www.w3schools.com/html/html5_semantic_elements.asp\\"},{\\"checked\\":false,\\"value\\":\\"Article: How To Write Semantic HTML https://hackernoon.com/how-to-write-semantic-html-dkq3ulo\\"},{\\"checked\\":false,\\"value\\":\\"Article: HTML Best Practices – How to Build a Better HTML-Based Website https://www.freecodecamp.org/news/html-best-practices/\\"},{\\"checked\\":false,\\"value\\":\\"Article: Semantic HTML: What It Is and How It Improves Your Site https://blog.hubspot.com/website/semantic-html\\"},{\\"checked\\":false,\\"value\\":\\"Article: Semantic Markup https://html.com/semantic-markup\\"},{\\"checked\\":false,\\"value\\":\\"Article: Semantic HTML - web.dev https://web.dev/learn/html/semantic-html/\\"},{\\"checked\\":false,\\"value\\":\\"Feed: Explore top posts about HTML https://app.daily.dev/tags/html?ref=roadmapsh\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":120}"	9f1eed82-3acf-4e07-a1bd-1f0b26cf1dca
824	c77582d0-b33d-4129-ac9b-773b409381b7	Accessibility	2024-07-09 16:52:12.737	4	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"Article: Developing for Web Accessibility by W3C WAI https://www.w3.org/WAI/tips/developing/\\"},{\\"checked\\":false,\\"value\\":\\"Article: Accessibility Tutorial https://www.w3schools.com/accessibility/index.php\\"},{\\"checked\\":false,\\"value\\":\\"Article: A Complete Guide To Accessible Front-End Components https://www.smashingmagazine.com/2021/03/complete-guide-accessible-front-end-components/\\"},{\\"checked\\":false,\\"value\\":\\"Article: MDN Accessibility https://developer.mozilla.org/en-US/docs/Web/Accessibility\\"},{\\"checked\\":false,\\"value\\":\\"Article: Accessibility for Developers by Google https://web.dev/accessibility\\"},{\\"checked\\":false,\\"value\\":\\"Course: Web Accessibility by Udacity https://www.udacity.com/course/web-accessibility--ud891\\"},{\\"checked\\":false,\\"value\\":\\"Article: Accessibility as an Essential Part of the Inclusive Developer Experience https://thenewstack.io/accessibility-as-an-essential-part-of-the-inclusive-developer-experience/\\"},{\\"checked\\":false,\\"value\\":\\"Video: Complete Playlist on Accessibility https://youtube.com/playlist?list=PLNYkxOF6rcICWx0C9LVWWVqvHlYJyqw7g\\"},{\\"checked\\":false,\\"value\\":\\"Feed: Explore top posts about Accessibility https://app.daily.dev/tags/accessibility?ref=roadmapsh\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":135}"	9f1eed82-3acf-4e07-a1bd-1f0b26cf1dca
825	93a9c38f-363e-4c82-9ca2-c332f6c8a63c	Basics of SEO	2024-07-09 16:52:12.737	5	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"GitHub: SEO Guide https://github.com/seo/guide\\"},{\\"checked\\":false,\\"value\\":\\"Article: Google Search Central — SEO Docs https://developers.google.com/search/docs\\"},{\\"checked\\":false,\\"value\\":\\"Article: 8 Must-Know SEO Best Practices For Developers https://neilpatel.com/blog/seo-developers/\\"},{\\"checked\\":false,\\"value\\":\\"Article: SEO for Developers https://medium.com/welldone-software/seo-for-developers-a-quick-overview-5b5b7ce34679\\"},{\\"checked\\":false,\\"value\\":\\"Article: Learning SEO https://learningseo.io/\\"},{\\"checked\\":false,\\"value\\":\\"Video: Complete SEO Course for Beginners https://www.youtube.com/watch?v=xsVTqzratPs\\"},{\\"checked\\":false,\\"value\\":\\"Video: SEO Expert Course https://www.youtube.com/watch?v=SnxeXZpZkI0\\"},{\\"checked\\":false,\\"value\\":\\"Feed: Explore top posts about SEO https://app.daily.dev/tags/seo?ref=roadmapsh\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":105}"	9f1eed82-3acf-4e07-a1bd-1f0b26cf1dca
826	35def577-b599-4085-8b5e-14f4931c24e3	Component Life Cycle	2024-07-09 16:52:12.737	1	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"official: Class Component https://react.dev/reference/react/Component\\"},{\\"checked\\":false,\\"value\\":\\"official: Lifecycle of Reactive Effects https://react.dev/learn/lifecycle-of-reactive-effects\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":40}"	42b9891a-48e2-4fba-89cc-d09cb494edc1
832	8f66f901-5226-4f86-8e8b-dbb681a50def	How Does The Internet Work	2024-07-09 16:52:12.737	1	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"Article: Introduction to Internet https://roadmap.sh/guides/what-is-internet\\"},{\\"checked\\":false,\\"value\\":\\"Article: How does the Internet Work? https://cs.fyi/guide/how-does-internet-work\\"},{\\"checked\\":false,\\"value\\":\\"Article: How Does the Internet Work? MDN Docs https://developer.mozilla.org/en-US/docs/Learn/Common_questions/How_does_the_Internet_work\\"},{\\"checked\\":false,\\"value\\":\\"Video: How does the Internet Work? https://www.youtube.com/watch?v=TNQsmPf24go\\"},{\\"checked\\":false,\\"value\\":\\"Video: How the Internet Works in 5 Minutes https://www.youtube.com/watch?v=7_LPdttKXPc\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":75}"	bc9836f9-5d40-4e51-9ad2-db08fddaf337
838	6b4a817e-5b23-4d2d-ab3f-d0b3e1849c66	CSS Basics	2024-07-09 16:52:12.737	1	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"Article: W3Schools — Learn CSS https://www.w3schools.com/css/\\"},{\\"checked\\":false,\\"value\\":\\"Article: web.dev — Learn CSS https://web.dev/learn/css/\\"},{\\"checked\\":false,\\"value\\":\\"Article: freeCodeCamp — Responsive Web Design https://www.freecodecamp.org/learn/responsive-web-design/\\"},{\\"checked\\":false,\\"value\\":\\"Article: Learn to Code HTML & CSS https://learn.shayhowe.com/html-css/building-your-first-web-page/\\"},{\\"checked\\":false,\\"value\\":\\"Video: CSS Crash Course For Absolute Beginners https://www.youtube.com/watch?v=yfoY53QXEnI\\"},{\\"checked\\":false,\\"value\\":\\"Video: HTML and CSS Tutorial https://www.youtube.com/watch?v=D-h8L5hgW-w\\"},{\\"checked\\":false,\\"value\\":\\"Video: CSS Masterclass - Tutorial & Course for Beginners https://www.youtube.com/watch?v=FqmB-Zj2-PA\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":105}"	7f645bfa-4e29-42b6-87ab-a598697b7488
843	d3ad897b-a1eb-456c-9ad8-bc4e3ada6e77	Redux / Toolkit	2024-07-09 16:52:12.737	3	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"article: Redux Toolkit - ReduxJS https://redux-toolkit.js.org/\\"},{\\"checked\\":false,\\"value\\":\\"article: Official Website https://redux.js.org/\\"},{\\"checked\\":false,\\"value\\":\\"article: Official Getting Started to Redux https://redux.js.org/introduction/getting-started\\"},{\\"checked\\":false,\\"value\\":\\"article: Redux Toolkit Official Website https://redux-toolkit.js.org\\"},{\\"checked\\":false,\\"value\\":\\"article: Official Tutorial to Learn Redux https://redux.js.org/tutorials/essentials/part-1-overview-concepts\\"},{\\"checked\\":false,\\"value\\":\\"video: Redux Tutorial - Beginner to Advanced https://youtube.com/watch?v=zrs7u6bdbUw\\"},{\\"checked\\":false,\\"value\\":\\"feed: Explore top posts about Redux https://app.daily.dev/tags/redux?ref=roadmapsh\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":140}"	bb19f59d-0578-443f-8995-22945fbbca14
848	301a171d-a4c9-461d-a560-cb731194ae23	CSS Modules	2024-07-09 16:52:12.737	3	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"GitHub: Project GitHub Repository https://github.com/css-modules/css-modules\\"},{\\"checked\\":false,\\"value\\":\\"article: Using CSS Modules In React App https://medium.com/@ralph1786/using-css-modules-in-react-app-c2079eadbb87\\"},{\\"checked\\":false,\\"value\\":\\"video: CSS Modules: Why are they great? https://www.youtube.com/watch?v=pKMWU9OrA2s\\"},{\\"checked\\":false,\\"value\\":\\"feed: Explore top posts about CSS https://app.daily.dev/tags/css?ref=roadmapsh\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":80}"	bd84ea8c-2b4b-4ee8-ba77-e589c20f3205
853	5b6a1dc7-05ab-4bb5-84c6-fea397ee00f9	Vitest	2024-07-09 16:52:12.737	2	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"official: Vitest Website https://vitest.dev/\\"},{\\"checked\\":false,\\"value\\":\\"video: Testing with Vitest https://www.youtube.com/watch?v=cM_AeQHzlGg\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":40}"	4024876d-f752-4f19-8138-de6560bde550
858	80fd1903-566a-4015-a450-a3a20fc74e89	REST - Axios	2024-07-09 16:52:12.737	3	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"article: Axios Getting Started https://axios-http.com/docs/intro\\"},{\\"checked\\":false,\\"value\\":\\"article: How To Use Axios With React: The Definitive Guide https://www.freecodecamp.org/news/how-to-use-axios-with-react/\\"},{\\"checked\\":false,\\"value\\":\\"article: How to make HTTP requests with Axios https://blog.logrocket.com/how-to-make-http-requests-like-a-pro-with-axios/#why\\"},{\\"checked\\":false,\\"value\\":\\"feed: Explore top posts about Axios https://app.daily.dev/tags/axios?ref=roadmapsh\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":80}"	f9cf0402-2942-423a-9f43-4dbc2542c5aa
864	4fdfb31f-e624-49eb-80ac-3cda57b485c5	Common Runtimes	2024-07-09 16:52:12.737	3	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"video: Big O Notation — Calculating Time Complexity https://www.youtube.com/watch?v=Z0bH0cMY0E8\\"},{\\"checked\\":false,\\"value\\":\\"video: Big O Notations https://www.youtube.com/watch?v=V6mKVRU1evU\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":40}"	0642eb50-30f7-444f-83f9-26d19c2f6801
871	70b28e7e-8f59-4d61-a5be-fb596065b114	Tree Traversal	2024-07-09 16:52:12.737	1	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"Article: Tree Traversals (Inorder, Preorder and Postorder) https://www.geeksforgeeks.org/tree-traversals-inorder-preorder-and-postorder/\\"},{\\"checked\\":false,\\"value\\":\\"Video: Tree | Illustrated Data Structures https://www.youtube.com/watch?v=S2W3SXGPVyU\\"},{\\"checked\\":false,\\"value\\":\\"Video: Pre-order tree traversal in 3 minutes https://www.youtube.com/watch?v=1WxLM2hwL-U\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":60}"	b6967039-a160-41e3-9fd5-e2b6f67facd7
877	ea03de28-21fe-44dd-a5e1-eb78f9f39303	JSX	2024-07-09 16:52:12.737	1	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"official: Writing markup with JSX https://react.dev/learn/writing-markup-with-jsx\\"},{\\"checked\\":false,\\"value\\":\\"official: JavaScript in JSX with Curly Braces https://react.dev/learn/javascript-in-jsx-with-curly-braces\\"},{\\"checked\\":false,\\"value\\":\\"article: JSX in React – Explained with Examples https://www.freecodecamp.org/news/jsx-in-react-introduction/\\"},{\\"checked\\":false,\\"value\\":\\"article: Working with JSX - React - CodeGuage https://www.codeguage.com/courses/react/jsx\\"},{\\"checked\\":false,\\"value\\":\\"article: JSX in React on w3school https://www.w3schools.com/react/react_jsx.asp\\"},{\\"checked\\":false,\\"value\\":\\"feed: Explore top posts about JSX https://app.daily.dev/tags/jsx?ref=roadmapsh\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":120}"	4df5271b-c434-4f59-ab8f-b249c2949f9e
882	0f69204b-173b-489a-a02c-a7564b697517	useEffect Hook	2024-07-09 16:52:12.737	6	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"official: Using the Effect Hook https://react.dev/reference/react/useEffect\\"},{\\"checked\\":false,\\"value\\":\\"article: React useEffect Hook by Example https://www.robinwieruch.de/react-useeffect-hook/\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":40}"	4df5271b-c434-4f59-ab8f-b249c2949f9e
827	8399e690-12b4-4457-a46f-ac6ed701f720	Lists and Keys	2024-07-09 16:52:12.737	2	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"official: Lists and Keys https://react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key\\"},{\\"checked\\":false,\\"value\\":\\"official: Rendering Lists https://react.dev/learn/rendering-lists\\"},{\\"checked\\":false,\\"value\\":\\"article: List components in React by Example https://www.robinwieruch.de/react-list-component/\\"},{\\"checked\\":false,\\"value\\":\\"article: Why do we need the key prop in React? https://www.robinwieruch.de/react-list-key/\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":80}"	42b9891a-48e2-4fba-89cc-d09cb494edc1
831	8a6a5438-f2ca-4acc-92f1-da2ca0354add	High Order Components	2024-07-09 16:52:12.737	6	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"article: High-Order Components https://reactjs.org/docs/higher-order-components.html\\"},{\\"checked\\":false,\\"value\\":\\"article: How to create a Higher-Order Component https://www.robinwieruch.de/react-higher-order-components/\\"},{\\"checked\\":false,\\"value\\":\\"video: Learn React Higher Order Component (HOC) in 10 Minutes https://youtu.be/J5P0q7EROfw?si=-8s5h1b0mZSGVgLt\\"},{\\"checked\\":false,\\"value\\":\\"video: ReactJS Tutorial - Higher Order Components (Part 1) https://www.youtube.com/watch?v=B6aNv8nkUSw\\"},{\\"checked\\":false,\\"value\\":\\"video: ReactJS Tutorial - Higher Order Components (Part 2) https://www.youtube.com/watch?v=rsBQj6X7UK8\\"},{\\"checked\\":false,\\"value\\":\\"video: ReactJS Tutorial - Higher Order Components (Part 3) https://www.youtube.com/watch?v=l8V59zIdBXU\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":120}"	42b9891a-48e2-4fba-89cc-d09cb494edc1
836	72b1f0f2-6b29-4e48-9fe2-8b793ac7d45f	What is DNS	2024-07-09 16:52:12.737	5	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"Article: What is DNS? https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/\\"},{\\"checked\\":false,\\"value\\":\\"Article: Mess with DNS - DNS Playground https://messwithdns.net/\\"},{\\"checked\\":false,\\"value\\":\\"Article: How DNS works (comic) https://howdns.works\\"},{\\"checked\\":false,\\"value\\":\\"Video: DNS and How does it Work? https://www.youtube.com/watch?v=WjDrMKZWCt0\\"},{\\"checked\\":false,\\"value\\":\\"Video: DNS Records https://www.youtube.com/watch?v=7lxgpKh_fRY\\"},{\\"checked\\":false,\\"value\\":\\"Video: When to add glue records to DNS settings https://www.youtube.com/watch?v=e48AyJOA9W8\\"},{\\"checked\\":false,\\"value\\":\\"Video: DNS Records for Newbies - How To Manage Website Records https://www.youtube.com/watch?v=YV5tkQYcvfg\\"},{\\"checked\\":false,\\"value\\":\\"Feed: Explore top posts about DNS https://app.daily.dev/tags/dns?ref=roadmapsh\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":120}"	bc9836f9-5d40-4e51-9ad2-db08fddaf337
840	75c5a8d9-8402-489b-8700-3dd14e782254	Responsive Web Design	2024-07-09 16:52:12.737	3	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"Article: Responsive Web Design https://www.w3schools.com/css/css_rwd_intro.asp\\"},{\\"checked\\":false,\\"value\\":\\"Article: Learn Responsive Design https://web.dev/learn/design/\\"},{\\"checked\\":false,\\"value\\":\\"Article: The Beginner’s Guide to Responsive Web Design https://kinsta.com/blog/responsive-web-design/\\"},{\\"checked\\":false,\\"value\\":\\"Article: The guide to responsive web design in 2022 https://webflow.com/blog/responsive-web-design\\"},{\\"checked\\":false,\\"value\\":\\"Video: 5 simple tips to making responsive layouts the easy way https://www.youtube.com/watch?v=VQraviuwbzU\\"},{\\"checked\\":false,\\"value\\":\\"Video: Introduction To Responsive Web Design https://www.youtube.com/watch?v=srvUrASNj0s\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":90}"	7f645bfa-4e29-42b6-87ab-a598697b7488
845	bff53eb8-b822-49fb-aece-95d6496ed0c1	Context	2024-07-09 16:52:12.737	5	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"official: Passing Data Deeply with Context https://react.dev/learn/passing-data-deeply-with-context\\"},{\\"checked\\":false,\\"value\\":\\"article: Basic useContext Guide https://www.w3schools.com/react/react_usecontext.asp\\"},{\\"checked\\":false,\\"value\\":\\"article: State with useContext and useState/useReducer https://www.robinwieruch.de/react-state-usereducer-usestate-usecontext/\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":60}"	bb19f59d-0578-443f-8995-22945fbbca14
850	000225c0-c3d5-4554-86ae-f0c43ad12659	Material UI	2024-07-09 16:52:12.737	5	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"article: Official Website https://mui.com/material-ui/\\"},{\\"checked\\":false,\\"value\\":\\"article: Official Documentation https://mui.com/material-ui/getting-started/\\"},{\\"checked\\":false,\\"value\\":\\"video: Material UI React Tutorial https://www.youtube.com/watch?v=o1chMISeTC0\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":60}"	bd84ea8c-2b4b-4ee8-ba77-e589c20f3205
855	66a7b011-13be-43af-be3f-4cf4f64e87fa	Cypress	2024-07-09 16:52:12.737	4	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"official: Official Website https://www.cypress.io/\\"},{\\"checked\\":false,\\"value\\":\\"article: Official Documentation https://docs.cypress.io/guides/overview/why-cypress#Other\\"},{\\"checked\\":false,\\"value\\":\\"video: Cypress End-to-End Testing https://www.youtube.com/watch?v=7N63cMKosIE\\"},{\\"checked\\":false,\\"value\\":\\"feed: Explore top posts about Cypress https://app.daily.dev/tags/cypress?ref=roadmapsh\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":80}"	4024876d-f752-4f19-8138-de6560bde550
860	649d2d1f-7783-45c1-9e35-cf047f862b36	GraphQL - Relay	2024-07-09 16:52:12.737	5	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"article: Apollo Website https://www.apollographql.com\\"},{\\"checked\\":false,\\"value\\":\\"article: Official Docs https://www.apollographql.com/docs/\\"},{\\"checked\\":false,\\"value\\":\\"video: Official YouTube Channel https://www.youtube.com/c/ApolloGraphQL/\\"},{\\"checked\\":false,\\"value\\":\\"video: GraphQL With React Tutorial - Apollo Client https://www.youtube.com/watch?v=YyUWW04HwKY\\"},{\\"checked\\":false,\\"value\\":\\"feed: Explore top posts about Apollo https://app.daily.dev/tags/apollo?ref=roadmapsh\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":100}"	f9cf0402-2942-423a-9f43-4dbc2542c5aa
866	bffbc514-84f9-4103-ba3c-e30f53fa22c6	Insertion Sort	2024-07-09 16:52:12.737	3	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"Article: Insertion Sort Algorithm https://www.programiz.com/dsa/insertion-sort\\"},{\\"checked\\":false,\\"value\\":\\"Video: Insertion Sort — MIT https://www.youtube.com/watch?v=Kg4bqzAqRBM&list=PLUl4u3cNGP61Oq3tWYp6V_F-5jb5L2iHb&index=4\\"},{\\"checked\\":false,\\"value\\":\\"Video: Insertion Sort in 3 Minutes https://www.youtube.com/watch?v=JU767SDMDvA\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":60}"	11961542-d821-4733-ab7e-075411a01a08
872	110fc5c8-c2d2-4320-a70d-0e5876e1d480	Tree Search	2024-07-09 16:52:12.737	2	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"Article: Tree Traversals (Inorder, Preorder and Postorder) https://www.geeksforgeeks.org/tree-traversals-inorder-preorder-and-postorder/\\"},{\\"checked\\":false,\\"value\\":\\"Video: Tree | Illustrated Data Structures https://www.youtube.com/watch?v=S2W3SXGPVyU\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":40}"	b6967039-a160-41e3-9fd5-e2b6f67facd7
876	823614f5-aaeb-45bf-b44a-83cec0070559	A* Algorithm	2024-07-09 16:52:12.737	6	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"Article: A* Search Algorithm - Wikipedia https://en.wikipedia.org/wiki/A*_search_algorithm\\"},{\\"checked\\":false,\\"value\\":\\"Video: A* Pathfinding (E01: algorithm explanation) https://www.youtube.com/watch?v=-L-WgKMFuhE\\"},{\\"checked\\":false,\\"value\\":\\"Feed: Explore top posts about Data Science https://app.daily.dev/tags/data-science?ref=roadmapsh\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":60}"	b6967039-a160-41e3-9fd5-e2b6f67facd7
881	3cd706a0-bb4b-414a-9ae3-bf0cda951431	useState Hook	2024-07-09 16:52:12.737	5	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"official: Using the State Hook https://react.dev/reference/react/useState\\"},{\\"checked\\":false,\\"value\\":\\"article: React useState Hook by Example https://www.robinwieruch.de/react-usestate-hook/\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":40}"	4df5271b-c434-4f59-ab8f-b249c2949f9e
828	85a8f9d7-dcc6-4ac9-805d-1d26bcc6d453	Render Props	2024-07-09 16:52:12.737	3	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"official: Render Props in React https://react.dev/learn/passing-props-to-a-component\\"},{\\"checked\\":false,\\"value\\":\\"article: How to create a Render Prop Component https://www.robinwieruch.de/react-render-props/\\"},{\\"checked\\":false,\\"value\\":\\"article: Render Props Pattern https://www.patterns.dev/posts/render-props-pattern/\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":60}"	42b9891a-48e2-4fba-89cc-d09cb494edc1
833	a17ad807-de15-4646-9147-ca57fcacaba5	What is HTTP	2024-07-09 16:52:12.737	2	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"Article: Everything you need to know about HTTP https://cs.fyi/guide/http-in-depth\\"},{\\"checked\\":false,\\"value\\":\\"Article: What is HTTP? https://www.cloudflare.com/en-gb/learning/ddos/glossary/hypertext-transfer-protocol-http/\\"},{\\"checked\\":false,\\"value\\":\\"Article: How HTTPS Works …in a comic! https://howhttps.works\\"},{\\"checked\\":false,\\"value\\":\\"Article: An overview of HTTP https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview\\"},{\\"checked\\":false,\\"value\\":\\"Article: HTTP/3 From A To Z: Core Concepts https://www.smashingmagazine.com/2021/08/http3-core-concepts-part1/\\"},{\\"checked\\":false,\\"value\\":\\"Article: HTTP/3 Is Now a Standard: Why Use It and How to Get Started https://thenewstack.io/http-3-is-now-a-standard-why-use-it-and-how-to-get-started/\\"},{\\"checked\\":false,\\"value\\":\\"Video: HTTP Crash Course & Exploration https://www.youtube.com/watch?v=iYM2zFP3Zn0\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":105}"	bc9836f9-5d40-4e51-9ad2-db08fddaf337
837	eb403d6c-99e7-43b7-b4a2-c1b5928bc930	How Browsers Work	2024-07-09 16:52:12.737	6	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"Article: How Browsers Work https://www.html5rocks.com/en/tutorials/internals/howbrowserswork/\\"},{\\"checked\\":false,\\"value\\":\\"Article: Role of Rendering Engine in Browsers https://www.browserstack.com/guide/browser-rendering-engine\\"},{\\"checked\\":false,\\"value\\":\\"Article: Populating the Page: How Browsers Work https://developer.mozilla.org/en-US/docs/Web/Performance/How_browsers_work\\"},{\\"checked\\":false,\\"value\\":\\"Video: How Do Web Browsers Work? https://www.youtube.com/watch?v=WjDrMKZWCt0\\"},{\\"checked\\":false,\\"value\\":\\"Feed: Explore top posts about Browsers https://app.daily.dev/tags/browsers?ref=roadmapsh\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":75}"	bc9836f9-5d40-4e51-9ad2-db08fddaf337
842	a12fafa0-be49-4f4a-9603-59c4f54dfabe	MobX	2024-07-09 16:52:12.737	2	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"article: MobX Official Website https://mobx.js.org/\\"},{\\"checked\\":false,\\"value\\":\\"video: Intro to MobX Tutorial https://www.youtube.com/watch?v=WQQq1QbYlAw\\"},{\\"checked\\":false,\\"value\\":\\"feed: Explore top posts about React https://app.daily.dev/tags/react?ref=roadmapsh\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":60}"	bb19f59d-0578-443f-8995-22945fbbca14
847	85016646-e71b-43e8-bf9b-95ed03bbc98f	Styled Components	2024-07-09 16:52:12.737	2	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"article: Official Website https://styled-components.com/\\"},{\\"checked\\":false,\\"value\\":\\"article: Official Docs https://styled-components.com/docs\\"},{\\"checked\\":false,\\"value\\":\\"article: Best Practices for Styled Components https://www.robinwieruch.de/styled-components/\\"},{\\"checked\\":false,\\"value\\":\\"video: Styled Components Crash Course & Project https://www.youtube.com/watch?v=02zO0hZmwnw\\"},{\\"checked\\":false,\\"value\\":\\"feed: Explore top posts about Styled Components https://app.daily.dev/tags/styled-components?ref=roadmapsh\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":100}"	bd84ea8c-2b4b-4ee8-ba77-e589c20f3205
851	b278f3de-9b66-4fb5-9dde-3d52fd47679d	Mantine	2024-07-09 16:52:12.737	6	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"official: Mantine Website https://mantine.dev/\\"},{\\"checked\\":false,\\"value\\":\\"official: Usage with Create React App https://mantine.dev/guides/cra/\\"},{\\"checked\\":false,\\"value\\":\\"article: 5 Mantine Hooks for UI management https://blog.logrocket.com/5-mantine-hooks-simplifying-ui-management-react/\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":60}"	bd84ea8c-2b4b-4ee8-ba77-e589c20f3205
857	2827da2b-eb27-4ebc-b3d9-8d04922846ac	Testing	2024-07-09 16:52:12.737	5	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"official: Official Website: Playwright https://playwright.dev/\\"},{\\"checked\\":false,\\"value\\":\\"article: Playwright Tutorial: Learn Basics and Setup https://www.browserstack.com/guide/playwright-tutorial\\"},{\\"checked\\":false,\\"value\\":\\"video: Get started with end-to-end testing: Playwright https://www.youtube.com/playlist?list=PLQ6Buerc008ed-F9OksF7ek37wR3y916p\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":60}"	4024876d-f752-4f19-8138-de6560bde550
863	a0931a6f-d281-4e2d-be0d-d6196c5e7328	Big Theta and Big Omega	2024-07-09 16:52:12.737	2	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"video: Big Oh Notation (and Omega and Theta) https://www.youtube.com/watch?v=ei-A_wy5Yxw&list=PL1BaGV1cIH4UhkL8a9bJGG356covJ76qN&index=3\\"},{\\"checked\\":false,\\"value\\":\\"video: Asymptotic Notation - CS50 https://www.youtube.com/watch?v=iOq5kSKqeR4\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":40}"	0642eb50-30f7-444f-83f9-26d19c2f6801
870	1eced2b4-8f03-46a4-859c-7740b56c1458	Merge Sort	2024-07-09 16:52:12.737	6	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"Article: Merge Sort - Geeks for Geeks https://www.geeksforgeeks.org/merge-sort/\\"},{\\"checked\\":false,\\"value\\":\\"Article: Merge Sort Algorithm https://www.programiz.com/dsa/merge-sort\\"},{\\"checked\\":false,\\"value\\":\\"Article: Merge Sort for Linked Lists https://www.geeksforgeeks.org/merge-sort-for-linked-list/\\"},{\\"checked\\":false,\\"value\\":\\"Video: Merge Sort in 3 Minutes https://www.youtube.com/watch?v=4VqmGXwpLqc\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":80}"	11961542-d821-4733-ab7e-075411a01a08
875	72fc7c7f-64db-4f28-b4a5-ebdc43e0c13b	Dijkstra's Algorithm	2024-07-09 16:52:12.737	5	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"Video: Dijkstras Algorithm - MIT https://www.youtube.com/watch?v=NSHizBK9JD8&t=1731s&ab_channel=MITOpenCourseWare\\"},{\\"checked\\":false,\\"value\\":\\"Video: Dijkstras Algorithm in 3 Minutes https://www.youtube.com/watch?v=_lHSawdgXpI\\"},{\\"checked\\":false,\\"value\\":\\"Feed: Explore top posts about Data Science https://app.daily.dev/tags/data-science?ref=roadmapsh\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":60}"	b6967039-a160-41e3-9fd5-e2b6f67facd7
878	92107845-cbe5-4457-bfd0-86729e48404a	Props vs State	2024-07-09 16:52:12.737	2	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"official: State: A Component’s Memory https://react.dev/learn/state-a-components-memory\\"},{\\"checked\\":false,\\"value\\":\\"article: How to use Props in React https://www.robinwieruch.de/react-pass-props-to-component/\\"},{\\"checked\\":false,\\"value\\":\\"article: What is the difference between state and props in React? https://stackoverflow.com/questions/27991366/what-is-the-difference-between-state-and-props-in-react\\"},{\\"checked\\":false,\\"value\\":\\"article: How to update state from props in React https://www.robinwieruch.de/react-derive-state-props/\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":80}"	4df5271b-c434-4f59-ab8f-b249c2949f9e
829	6047504f-eb97-4bb5-9d0c-cfeb85d7bb11	Refs	2024-07-09 16:52:12.737	4	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"official: Referencing Values with Refs https://react.dev/learn/referencing-values-with-refs\\"},{\\"checked\\":false,\\"value\\":\\"official: Manipulating the DOM with Refs https://react.dev/learn/manipulating-the-dom-with-refs\\"},{\\"checked\\":false,\\"value\\":\\"article: Examples of using refs in React https://www.robinwieruch.de/react-ref/\\"},{\\"checked\\":false,\\"value\\":\\"article: The Complete Guide to useRef() and Refs in React https://dmitripavlutin.com/react-useref-guide/\\"},{\\"checked\\":false,\\"value\\":\\"article: What Exactly Are Refs? - React - CodeGuage https://www.codeguage.com/courses/react/refs\\"},{\\"checked\\":false,\\"value\\":\\"video: Learn useRef in 11 Minutes - Web Dev Simplified https://www.youtube.com/watch?v=t2ypzz6gJm0\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":120}"	42b9891a-48e2-4fba-89cc-d09cb494edc1
835	ab4a9fd2-f5a4-41b4-a776-7f2bf4606ee3	What is Hosting	2024-07-09 16:52:12.737	4	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"Video: What Is Web Hosting? Explained https://www.youtube.com/watch?v=htbY9-yggB0\\"},{\\"checked\\":false,\\"value\\":\\"Video: Different Types of Web Hosting Explained https://www.youtube.com/watch?v=AXVZYzw8geg\\"},{\\"checked\\":false,\\"value\\":\\"Video: Where to Host a Fullstack Project on a Budget https://www.youtube.com/watch?v=Kx_1NYYJS7Q\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":45}"	bc9836f9-5d40-4e51-9ad2-db08fddaf337
839	d287eba6-d5aa-4d09-8f35-b4a60292250c	Making Layouts	2024-07-09 16:52:12.737	2	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"Course: Learn CSS Grid for free https://scrimba.com/learn/cssgrid\\"},{\\"checked\\":false,\\"value\\":\\"Article: Learn and Practice Flexbox https://flexboxfroggy.com/\\"},{\\"checked\\":false,\\"value\\":\\"Article: Game for learning CSS Grid https://cssgridgarden.com/\\"},{\\"checked\\":false,\\"value\\":\\"Article: All about Floats https://css-tricks.com/all-about-floats/\\"},{\\"checked\\":false,\\"value\\":\\"Article: Positioning Types: How Do They Differ? https://css-tricks.com/absolute-relative-fixed-positioining-how-do-they-differ/\\"},{\\"checked\\":false,\\"value\\":\\"Article: The Box Model https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model\\"},{\\"checked\\":false,\\"value\\":\\"Article: The CSS Display Property https://www.freecodecamp.org/news/the-css-display-property-display-none-display-table-inline-block-and-more/\\"},{\\"checked\\":false,\\"value\\":\\"Article: A Complete Guide to Flexbox https://css-tricks.com/snippets/css/a-guide-to-flexbox\\"},{\\"checked\\":false,\\"value\\":\\"Article: A Complete Guide to Grid https://css-tricks.com/snippets/css/complete-guide-grid\\"},{\\"checked\\":false,\\"value\\":\\"Course: Learn CSS Grid https://cssgrid.io/\\"},{\\"checked\\":false,\\"value\\":\\"Article: Get on the Grid at Last with the CSS Grid Layout Module https://thenewstack.io/get-grid-last-css-grid-template-markup/\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":165}"	7f645bfa-4e29-42b6-87ab-a598697b7488
844	6616dfb7-a96b-46c6-8f16-653873469117	Zustand	2024-07-09 16:52:12.737	4	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"GitHub: Zustand - Official Website https://github.com/pmndrs/zustand\\"},{\\"checked\\":false,\\"value\\":\\"GitHub: Zustand Repository https://github.com/pmndrs/zustand\\"},{\\"checked\\":false,\\"value\\":\\"article: Working with Zustand https://tkdodo.eu/blog/working-with-zustand\\"},{\\"checked\\":false,\\"value\\":\\"article: Zustand - Official Documentation https://docs.pmnd.rs/zustand/getting-started/introduction\\"},{\\"checked\\":false,\\"value\\":\\"video: Zustand Tutorial for Beginners https://www.youtube.com/watch?v=AYO4qHAnLQI&t\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":100}"	bb19f59d-0578-443f-8995-22945fbbca14
849	564107f8-52b9-43d6-a1ea-62f472baa237	TailwindCSS	2024-07-09 16:52:12.737	4	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"article: Tailwind Website https://tailwindcss.com\\"},{\\"checked\\":false,\\"value\\":\\"video: Tailwind CSS Full Course for Beginners https://www.youtube.com/watch?v=lCxcTsOHrjo\\"},{\\"checked\\":false,\\"value\\":\\"video: Tailwind CSS Crash Course https://www.youtube.com/watch?v=UBOj6rqRUME\\"},{\\"checked\\":false,\\"value\\":\\"video: Should You Use Tailwind CSS? https://www.youtube.com/watch?v=hdGsFpZ0J2E\\"},{\\"checked\\":false,\\"value\\":\\"video: Official Screencasts https://www.youtube.com/c/TailwindLabs/videos\\"},{\\"checked\\":false,\\"value\\":\\"feed: Explore top posts about Tailwind CSS https://app.daily.dev/tags/tailwind-css?ref=roadmapsh\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":120}"	bd84ea8c-2b4b-4ee8-ba77-e589c20f3205
854	30fdadcc-9d7b-4673-9b05-397393f4eca2	React Testing Library	2024-07-09 16:52:12.737	3	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"article: React Testing Library https://testing-library.com/docs/react-testing-library/intro/\\"},{\\"checked\\":false,\\"value\\":\\"article: How to use React Testing Library https://www.robinwieruch.de/react-testing-library/\\"},{\\"checked\\":false,\\"value\\":\\"feed: Explore top posts about React https://app.daily.dev/tags/react?ref=roadmapsh\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":60}"	4024876d-f752-4f19-8138-de6560bde550
859	c003775e-5193-4984-9fa8-60f32930543e	GraphQL - Apollo	2024-07-09 16:52:12.737	4	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"article: Apollo Website https://www.apollographql.com\\"},{\\"checked\\":false,\\"value\\":\\"article: Official Docs https://www.apollographql.com/docs/\\"},{\\"checked\\":false,\\"value\\":\\"video: Official YouTube Channel https://www.youtube.com/c/ApolloGraphQL/\\"},{\\"checked\\":false,\\"value\\":\\"video: GraphQL With React Tutorial - Apollo Client https://www.youtube.com/watch?v=YyUWW04HwKY\\"},{\\"checked\\":false,\\"value\\":\\"feed: Explore top posts about Apollo https://app.daily.dev/tags/apollo?ref=roadmapsh\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":100}"	f9cf0402-2942-423a-9f43-4dbc2542c5aa
865	e90124cc-d023-47e2-be27-58b9929a7fc7	Bubble Sort	2024-07-09 16:52:12.737	1	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"Video: Bubble Sort https://www.youtube.com/watch?v=P00xJgWzz2c&index=1&list=PL89B61F78B552C1AB\\"},{\\"checked\\":false,\\"value\\":\\"Video: Analyzing Bubble Sort https://www.youtube.com/watch?v=ni_zk257Nqo&index=7&list=PL89B61F78B552C1AB\\"},{\\"checked\\":false,\\"value\\":\\"Video: Bubble sort in 2 minutes https://youtu.be/xli_FI7CuzA\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":60}"	11961542-d821-4733-ab7e-075411a01a08
869	db29bf3d-cc6f-4938-a93d-e6a361e0e96d	Quick Sort	2024-07-09 16:52:12.737	5	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"GitHub: Quick Sort Implementation in Python https://github.com/jwasham/practice-python/blob/master/quick_sort/quick_sort.py\\"},{\\"checked\\":false,\\"value\\":\\"Article: Quick Sort Algorithm https://www.programiz.com/dsa/quick-sort\\"},{\\"checked\\":false,\\"value\\":\\"Article: Quick Sort Algorithm - Geeks for Geeks https://www.geeksforgeeks.org/quick-sort/\\"},{\\"checked\\":false,\\"value\\":\\"Article: Quick Sort Implementation in C http://www.cs.yale.edu/homes/aspnes/classes/223/examples/randomization/quick.c\\"},{\\"checked\\":false,\\"value\\":\\"Video: Quick Sort in 4 Minutes https://www.youtube.com/watch?v=Hoixgm4-P4M&feature=youtu.be\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":100}"	11961542-d821-4733-ab7e-075411a01a08
874	1717efa0-9006-4470-b073-5b9a2680800f	Bellman Ford's Algorithm	2024-07-09 16:52:12.737	4	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"Video: Bellman-Ford - MIT https://www.youtube.com/watch?v=f9cVS_URPc0&ab_channel=MITOpenCourseWare\\"},{\\"checked\\":false,\\"value\\":\\"Video: Bellman-Ford in 4 Minutes https://www.youtube.com/watch?v=9PHkk0UavIM\\"},{\\"checked\\":false,\\"value\\":\\"Feed: Explore top posts about Data Science https://app.daily.dev/tags/data-science?ref=roadmapsh\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":60}"	b6967039-a160-41e3-9fd5-e2b6f67facd7
830	5ecd9264-84f6-40c9-86dc-b3f38131312f	Events	2024-07-09 16:52:12.737	5	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"official: Responding to Events https://react.dev/learn/responding-to-events\\"},{\\"checked\\":false,\\"value\\":\\"official: React Event Object (Synthetic Event) https://react.dev/reference/react-dom/components/common#react-event-object\\"},{\\"checked\\":false,\\"value\\":\\"article: React Event Handler https://www.robinwieruch.de/react-event-handler/\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":60}"	42b9891a-48e2-4fba-89cc-d09cb494edc1
834	260fef20-9eab-4352-8104-b99b7c92f502	What is a Domain Name	2024-07-09 16:52:12.737	3	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"Article: What is a Domain Name? https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_domain_name\\"},{\\"checked\\":false,\\"value\\":\\"Article: What is a Domain Name? | Domain name vs. URL https://www.cloudflare.com/en-gb/learning/dns/glossary/what-is-a-domain-name/\\"},{\\"checked\\":false,\\"value\\":\\"Video: A Beginners Guide to How Domain Names Work https://www.youtube.com/watch?v=Y4cRx19nhJk\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":45}"	bc9836f9-5d40-4e51-9ad2-db08fddaf337
841	9c72c8a4-cfc0-4425-abed-38bb478c6bd4	Recoil	2024-07-09 16:52:12.737	1	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"article: Recoil - Official Website https://recoiljs.org/\\"},{\\"checked\\":false,\\"value\\":\\"feed: Explore top posts about React https://app.daily.dev/tags/react?ref=roadmapsh\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":40}"	bb19f59d-0578-443f-8995-22945fbbca14
846	f97f21c4-b572-4a00-bc4b-1a95d7c4f977	Emotion	2024-07-09 16:52:12.737	1	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"official: Official Website and Docs https://emotion.sh/docs/introduction\\"},{\\"checked\\":false,\\"value\\":\\"video: Styled components using emotion in React https://www.youtube.com/watch?v=yO3JU2bMLGA\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":40}"	bd84ea8c-2b4b-4ee8-ba77-e589c20f3205
852	ff48735d-07b3-4e81-93d5-4f9b0af5ac78	Jest	2024-07-09 16:52:12.737	1	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"article: Jest Website https://jestjs.io/\\"},{\\"checked\\":false,\\"value\\":\\"feed: Explore top posts about Jest https://app.daily.dev/tags/jest?ref=roadmapsh\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":40}"	4024876d-f752-4f19-8138-de6560bde550
856	1ac237d1-3f6f-4aa3-98fe-64dc01a249b4	REST - SWR	2024-07-09 16:52:12.737	1	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"article: SWR: React Hooks for Data Fetching https://swr.vercel.app/\\"},{\\"checked\\":false,\\"value\\":\\"feed: Explore top posts about Next.js https://app.daily.dev/tags/nextjs?ref=roadmapsh\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":40}"	f9cf0402-2942-423a-9f43-4dbc2542c5aa
861	82c11a96-0a8e-4b17-92b3-a9759aee4ac3	Big O Notation	2024-07-09 16:52:12.737	1	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"article: CS 61B Lecture 19: Asymptotic Analysis https://archive.org/details/ucberkeley_webcast_VIS4YDpuP98\\"},{\\"checked\\":false,\\"value\\":\\"video: Big O Notation — Calculating Time Complexity https://www.youtube.com/watch?v=Z0bH0cMY0E8\\"},{\\"checked\\":false,\\"value\\":\\"video: Big O Notations https://www.youtube.com/watch?v=V6mKVRU1evU\\"},{\\"checked\\":false,\\"value\\":\\"video: Big Oh Notation (and Omega and Theta) https://www.youtube.com/watch?v=ei-A_wy5Yxw&list=PL1BaGV1cIH4UhkL8a9bJGG356covJ76qN&index=3\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":80}"	0642eb50-30f7-444f-83f9-26d19c2f6801
867	af35c7bf-1e8c-4e74-9baf-a581022e3f19	Selection Sort	2024-07-09 16:52:12.737	2	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"Course: Selection Sort https://www.coursera.org/lecture/algorithms-part1/selection-UQxFT\\"},{\\"checked\\":false,\\"value\\":\\"Video: Selection Sort in 3 Minutes https://www.youtube.com/watch?v=g-PGLbMth_g\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":40}"	11961542-d821-4733-ab7e-075411a01a08
873	a9a1dd84-a8f3-4246-abcd-e5f41a85a31d	Graph Search	2024-07-09 16:52:12.737	3	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"Article: Breadth First Search or BFS for a Graph https://www.geeksforgeeks.org/breadth-first-search-or-bfs-for-a-graph/\\"},{\\"checked\\":false,\\"value\\":\\"Video: Graph Algorithms II - DFS, BFS, Kruskals Algorithm, Union Find Data Structure - Lecture 7 https://www.youtube.com/watch?v=ufj5_bppBsA&list=PLFDnELG9dpVxQCxuD-9BSy2E7BWY3t5Sm&index=7\\"},{\\"checked\\":false,\\"value\\":\\"Video: Breadth-first search in 4 minutes https://www.youtube.com/watch?v=hz5ytanv5qe\\"},{\\"checked\\":false,\\"value\\":\\"Article: Depth First Search or DFS for a Graph https://www.geeksforgeeks.org/depth-first-search-or-dfs-for-a-graph/?ref=lbp\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":80}"	b6967039-a160-41e3-9fd5-e2b6f67facd7
879	99228e24-0327-47e8-9626-e3e5f12c9bf3	Conditional Rendering	2024-07-09 16:52:12.737	3	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"official: Conditional Rendering https://react.dev/learn/conditional-rendering\\"},{\\"checked\\":false,\\"value\\":\\"article: Different techniques for conditional rendering in React https://www.robinwieruch.de/conditional-rendering-react/\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":40}"	4df5271b-c434-4f59-ab8f-b249c2949f9e
862	b1fd1d66-8ef5-4a3b-9950-d38d1af971d2	REST - react-query	2024-07-09 16:52:12.737	2	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"GitHub: TanStack Query https://github.com/TanStack/query\\"},{\\"checked\\":false,\\"value\\":\\"video: React Query in 100 Seconds https://www.youtube.com/watch?v=novnyCaa7To\\"},{\\"checked\\":false,\\"value\\":\\"video: React Query Tutorial for Beginners - Complete Playlist https://www.youtube.com/playlist?list=PLC3y8-rFHvwjTELCrPrcZlo6blLBUspd2\\"},{\\"checked\\":false,\\"value\\":\\"feed: Explore top posts about React https://app.daily.dev/tags/react?ref=roadmapsh\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":80}"	f9cf0402-2942-423a-9f43-4dbc2542c5aa
868	d297e87f-aea7-4b4b-a7b1-28efc96bfbf5	Heap Sort	2024-07-09 16:52:12.737	4	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"Course: Heap Sort Algorithm https://www.coursera.org/lecture/data-structures/heap-sort-hSzMO\\"},{\\"checked\\":false,\\"value\\":\\"Article: Heap Sort Algorithm https://www.programiz.com/dsa/heap-sort\\"},{\\"checked\\":false,\\"value\\":\\"Article: Heap Sort Algorithm - Geeks for Geeks https://www.geeksforgeeks.org/heap-sort/\\"},{\\"checked\\":false,\\"value\\":\\"Video: Heap Sort in 4 Minutes https://www.youtube.com/watch?v=2DmK_H7IdTo\\"},{\\"checked\\":false,\\"value\\":\\"Video: Heap Sort Algorithm - MIT https://www.youtube.com/watch?v=odNJmw5TOEE&list=PLFDnELG9dpVxQCxuD-9BSy2E7BWY3t5Sm&t=3291s\\"},{\\"checked\\":false,\\"value\\":\\"Video: Lecture 4 - Heaps and Heap Sort https://www.youtube.com/watch?v=B7hVxCmfPtM&list=PLUl4u3cNGP61Oq3tWYp6V_F-5jb5L2iHb&index=5\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":120}"	11961542-d821-4733-ab7e-075411a01a08
880	ee0a5af6-8b14-4c03-8117-8d109f82b8ae	Composition vs Inheritance	2024-07-09 16:52:12.737	4	Backlog	"{\\"checklist\\":[{\\"checked\\":false,\\"value\\":\\"official: Passing JSX as children https://react.dev/learn/passing-props-to-a-component#passing-jsx-as-children\\"},{\\"checked\\":false,\\"value\\":\\"article: Composition vs Inheritance https://reactjs.org/docs/composition-vs-inheritance.html\\"},{\\"checked\\":false,\\"value\\":\\"article: How to perform component composition in React https://www.robinwieruch.de/react-component-composition/\\"},{\\"checked\\":false,\\"value\\":\\"article: Achieving Reusability With React Composition https://formidable.com/blog/2021/react-composition/\\"}],\\"notes\\":\\"\\",\\"timeEstimate\\":80}"	4df5271b-c434-4f59-ab8f-b249c2949f9e
\.


--
-- Name: template_cards_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.template_cards_id_seq', 882, true);


--
-- Name: template_cards template_cards_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.template_cards
    ADD CONSTRAINT template_cards_pkey PRIMARY KEY (id);


--
-- Name: template_cards template_cards_board_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.template_cards
    ADD CONSTRAINT template_cards_board_id_fkey FOREIGN KEY (board_id) REFERENCES public.templates(uuid) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

